   before:
     hooks:
       - go generate ./...
       - make build
   
   builds:
   - env:
       - CGO_ENABLED=0
     main: ./cmd/promc
     goos:
       - linux
       - darwin
       - windows
     goarch:
       - amd64
       - arm64
   
   checksum:
     name_template: 'checksums.txt'
   
   snapshot:
     name_template: "{{ .Tag }}-next"
   
   changelog:
     sort: asc
     filters:
       exclude:
       - '^wiki:'
       - '^test:'
       - '^docs:'

