// Code generated by go generate; DO NOT EDIT.
package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
)

func init() {
	// Automatically register metrics with Prometheus's default registry.

	prometheus.MustRegister(SystemUptimeSeconds)
	prometheus.MustRegister(HttpRequestsTotal)
	prometheus.MustRegister(HttpRequestDurationSeconds)
	prometheus.MustRegister(ActiveSessions)
}

var SystemUptimeSeconds = prometheus.NewGauge(
	prometheus.GaugeOpts{
		Name: "system_uptime_seconds",
		Help: "The total system uptime in seconds.",
	},
)

func SetSystemUptimeSeconds(value float64) {
	SystemUptimeSeconds.Set(value)
}

type HttpRequestsTotalLabels struct {
	Method string
	Status string
}

var HttpRequestsTotal = prometheus.NewCounterVec(
	prometheus.CounterOpts{
		Name: "http_requests_total",
		Help: "The total number of HTTP requests.",
	},
	[]string{"method", "status"},
)

func IncHttpRequestsTotal(labels HttpRequestsTotalLabels) {
	HttpRequestsTotal.With(prometheus.Labels{
		"method": labels.Method,
		"status": labels.Status,
	}).Inc()
}

type HttpRequestDurationSecondsLabels struct {
	Method string
	Status string
}

var HttpRequestDurationSeconds = prometheus.NewHistogramVec(
	prometheus.HistogramOpts{
		Name:    "http_request_duration_seconds",
		Help:    "The duration of HTTP requests in seconds.",
		Buckets: []float64{0.001, 0.01, 0.1, 0.5, 1, 5, 10},
	},
	[]string{"method", "status"},
)

func ObserveHttpRequestDurationSeconds(labels HttpRequestDurationSecondsLabels, value float64) {
	HttpRequestDurationSeconds.With(prometheus.Labels{
		"method": labels.Method,
		"status": labels.Status,
	}).Observe(value)
}

type ActiveSessionsLabels struct {
	UserType string
}

var ActiveSessions = prometheus.NewGaugeVec(
	prometheus.GaugeOpts{
		Name: "active_sessions",
		Help: "The current number of active sessions.",
	},
	[]string{"user_type"},
)

func SetActiveSessions(labels ActiveSessionsLabels, value float64) {
	ActiveSessions.With(prometheus.Labels{
		"user_type": labels.UserType,
	}).Set(value)
}
